// Derive a SQLite schema for local development from the real one.
//
// Production runs Postgres: a container filesystem is wiped on every redeploy, so a
// SQLite file there would lose every session. Locally the opposite is true — nobody
// wants to run a Postgres just to click through the app, and this machine has neither
// Docker nor psql.
//
// Prisma will not let `provider` come from an environment variable (tested: it fails
// validation), so the two environments genuinely need two schema files. Rather than
// commit a second one and watch it drift out of sync the first time a model changes,
// this generates it from prisma/schema.prisma on every `shopify app dev`. There is
// exactly one source of truth, and the copy is gitignored.
//
// Migrations stay Postgres-only. Local uses `prisma db push`, which builds the
// database straight from the models and needs no migration history.

import fs from "fs";
import path from "path";
import { fileURLToPath } from "url";

const ROOT = path.join(path.dirname(fileURLToPath(import.meta.url)), "..");
const SOURCE = path.join(ROOT, "prisma", "schema.prisma");
const OUT_DIR = path.join(ROOT, "prisma", "dev");
const OUT = path.join(OUT_DIR, "schema.prisma");

const source = fs.readFileSync(SOURCE, "utf8");

const DATASOURCE = /datasource\s+db\s*\{[^}]*\}/;
if (!DATASOURCE.test(source)) {
  console.error(
    "dev-schema: no `datasource db { ... }` block in prisma/schema.prisma — did it move?",
  );
  process.exit(1);
}

const derived =
  "// GENERATED by scripts/dev-schema.mjs — do not edit.\n" +
  "// Edit prisma/schema.prisma instead; this file is rewritten on every dev run.\n\n" +
  source.replace(
    DATASOURCE,
    'datasource db {\n  provider = "sqlite"\n  url      = env("DATABASE_URL")\n}',
  );

fs.mkdirSync(OUT_DIR, { recursive: true });

// Only write when it actually changed, so the file's mtime stays meaningful and a
// watcher doesn't see a change on every single run.
if (!fs.existsSync(OUT) || fs.readFileSync(OUT, "utf8") !== derived) {
  fs.writeFileSync(OUT, derived);
  console.log("dev-schema: wrote prisma/dev/schema.prisma (sqlite)");
} else {
  console.log("dev-schema: prisma/dev/schema.prisma already current");
}
